import { useState } from 'react'
import { FileBarChart, Download, Eye, Plus } from 'lucide-react'
import { StatusBadge } from '../components/shared/StatusBadge'
import { KPICard } from '../components/shared/KPICard'
import { reports } from '../data/risk-alerts'
import { formatDate } from '../lib/utils'

const reportTypeLabels: Record<string, string> = {
  COMPLIANCE: 'Compliance',
  RISK_ASSESSMENT: 'Risk Assessment',
  INSPECTION_SUMMARY: 'Inspection Summary',
  CAPA_STATUS: 'CAPA Status',
  MONTHLY_REVIEW: 'Monthly Review',
  DGMS_RETURN: 'DGMS Return',
}

export default function Reports() {
  const [typeFilter, setTypeFilter] = useState<string>('ALL')
  const [showGenerateModal, setShowGenerateModal] = useState(false)

  const filtered = typeFilter === 'ALL' ? reports : reports.filter((r) => r.type === typeFilter)

  return (
    <div className="space-y-5">
      {/* KPIs */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <KPICard label="Total Reports" value={reports.length} icon={<FileBarChart className="w-4 h-4" />} />
        <KPICard label="Generated" value={reports.filter((r) => r.status === 'GENERATED').length} variant="success" />
        <KPICard label="Drafts" value={reports.filter((r) => r.status === 'DRAFT').length} />
        <KPICard label="Submitted" value={reports.filter((r) => r.status === 'SUBMITTED' || r.status === 'APPROVED').length} variant="success" />
      </div>

      {/* Actions */}
      <div className="flex items-center justify-between">
        <select
          value={typeFilter}
          onChange={(e) => setTypeFilter(e.target.value)}
          className="px-3 py-2 bg-surface-raised border border-border rounded text-[12px] text-text-secondary focus:outline-none"
        >
          <option value="ALL">All Report Types</option>
          {Object.entries(reportTypeLabels).map(([key, label]) => (
            <option key={key} value={key}>{label}</option>
          ))}
        </select>
        <button
          onClick={() => setShowGenerateModal(true)}
          className="flex items-center gap-1.5 px-4 py-2 bg-amber text-mine-black text-[12px] font-medium rounded hover:bg-amber-light transition-colors"
        >
          <Plus className="w-3.5 h-3.5" /> Generate Report
        </button>
      </div>

      {/* Reports Table */}
      <div className="bg-surface-raised border border-border rounded overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead>
              <tr className="border-b border-border bg-mine-black/50">
                <th className="px-4 py-3 text-[11px] font-semibold text-text-muted uppercase tracking-wider">Report Name</th>
                <th className="px-4 py-3 text-[11px] font-semibold text-text-muted uppercase tracking-wider">Type</th>
                <th className="px-4 py-3 text-[11px] font-semibold text-text-muted uppercase tracking-wider">Period</th>
                <th className="px-4 py-3 text-[11px] font-semibold text-text-muted uppercase tracking-wider">Generated</th>
                <th className="px-4 py-3 text-[11px] font-semibold text-text-muted uppercase tracking-wider">Generated By</th>
                <th className="px-4 py-3 text-[11px] font-semibold text-text-muted uppercase tracking-wider">Status</th>
                <th className="px-4 py-3 text-[11px] font-semibold text-text-muted uppercase tracking-wider">Size</th>
                <th className="px-4 py-3 text-[11px] font-semibold text-text-muted uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {filtered.map((report) => (
                <tr key={report.id} className="hover:bg-mine-black/50 transition-colors">
                  <td className="px-4 py-3">
                    <p className="text-[12px] font-medium text-text-primary">{report.name}</p>
                    {report.mineName && (
                      <p className="text-[11px] text-text-muted">{report.mineName}</p>
                    )}
                  </td>
                  <td className="px-4 py-3 text-[12px] text-text-secondary">
                    {reportTypeLabels[report.type] || report.type}
                  </td>
                  <td className="px-4 py-3 text-[12px] text-text-secondary">{report.period}</td>
                  <td className="px-4 py-3 text-[12px] font-mono text-text-secondary">{formatDate(report.generatedDate)}</td>
                  <td className="px-4 py-3 text-[12px] text-text-secondary">{report.generatedBy}</td>
                  <td className="px-4 py-3"><StatusBadge status={report.status} /></td>
                  <td className="px-4 py-3 text-[12px] font-mono text-text-muted">{report.fileSize}</td>
                  <td className="px-4 py-3">
                    <div className="flex gap-1">
                      <button className="p-1.5 text-text-muted hover:text-text-primary transition-colors" title="Preview">
                        <Eye className="w-3.5 h-3.5" />
                      </button>
                      <button className="p-1.5 text-text-muted hover:text-amber transition-colors" title="Download">
                        <Download className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Generate Report Modal */}
      {showGenerateModal && (
        <>
          <div className="fixed inset-0 bg-black/60 z-50" onClick={() => setShowGenerateModal(false)} />
          <div className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[480px] bg-surface-raised border border-border rounded-lg shadow-2xl z-50 p-6">
            <h3 className="font-heading text-[18px] font-bold text-text-primary tracking-wide mb-4">GENERATE NEW REPORT</h3>
            <div className="space-y-4">
              <div>
                <label className="text-[11px] text-text-muted uppercase tracking-wider">Report Type</label>
                <select className="w-full mt-1 px-3 py-2 bg-mine-black border border-border rounded text-[13px] text-text-primary focus:outline-none focus:border-amber/50">
                  {Object.entries(reportTypeLabels).map(([key, label]) => (
                    <option key={key} value={key}>{label}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="text-[11px] text-text-muted uppercase tracking-wider">Period</label>
                <input
                  type="text"
                  defaultValue="September 2026"
                  className="w-full mt-1 px-3 py-2 bg-mine-black border border-border rounded text-[13px] text-text-primary focus:outline-none focus:border-amber/50"
                />
              </div>
              <div>
                <label className="text-[11px] text-text-muted uppercase tracking-wider">Mine (Optional)</label>
                <select className="w-full mt-1 px-3 py-2 bg-mine-black border border-border rounded text-[13px] text-text-primary focus:outline-none focus:border-amber/50">
                  <option value="">All Mines</option>
                  <option value="mine-wcl-04">WCL-04 — Wani Opencast Extension</option>
                  <option value="mine-secl-07">SECL-07 — Gevra Opencast Project</option>
                </select>
              </div>
              <div className="flex gap-2 justify-end pt-2">
                <button onClick={() => setShowGenerateModal(false)} className="px-4 py-2 text-[12px] text-text-secondary hover:text-text-primary transition-colors">
                  Cancel
                </button>
                <button
                  onClick={() => {
                    setShowGenerateModal(false)
                    alert('Report generation initiated (demo). In production, this would trigger the report generation pipeline.')
                  }}
                  className="px-4 py-2 bg-amber text-mine-black text-[12px] font-medium rounded hover:bg-amber-light transition-colors"
                >
                  Generate
                </button>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  )
}
